wandb:
    entity: naver-inapp
    project: final_organization
    group: ensemble
    name: T5encoder/decoder

data:
    train_path: data/train.csv
    dev_path: data/dev.csv
    test_path: data/test.csv
    shuffle: True
    
model:
    model_name : KETI-AIR/ke-t5-large-ko
    data_class : T5Dataset
    model_class : T5Model
    trainer: T5Trainer
    saved_name: T5encoder/decoder
    loss : Huber_loss
    metric : pearson_correlation
    optimizer : optim_AdamW
    dropout_rate : 0.2

train:
    seed: 2022
    gpus: 1
    batch_size: 8
    max_epoch: 10
    learning_rate: 5e-5
    logging_step: 1
    max_length : 180